db:
  image: mongo
  ports:
    - "27017:27017"
  restart: always
node:
  image: "node:8"

  volumes:
    - ./:/usr/src/app
  expose:
    - "8080"
web:
  build: .
  environment:
    - NODE_ENV=production
  volumes:
    - .:/admin
    - .:/client
    - .:/server
  ports:
    - "4200:4200"
  tty: true
  links:
    - db
  command: node_modules/.bin/nodemon server/index.js
