version: "3.2"
services:
  server:
    image: matty0187/illuminism-platform-admin
    volumes:
      - ./server/src:/var/www/src
    ports:
      - 4202:8191
    networks:
      - nodeapp-network

  client:
    image: matty0187/illuminism-platform-client
    volumes:
      - ./client:/app
    ports:
      - 4200:4200
    working_dir: /app
    networks:
      - nodeapp-network
    command: ng serve --host 0.0.0.0 --port 4200

  admin:
    image: matty0187/illuminism-platform-client
    volumes:
      - ./admin:/app
    ports:
      - 4201:4201
    working_dir: /app
    networks:
      - nodeapp-network
    command: ng serve --host 0.0.0.0 --port 4201
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
